apiVersion: apps/v1
kind: Deployment
metadata:
  name: SpringBootApplication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: springboot-container
          image: dinesh111dj/devops-integration:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30040
  selector:
    app: spring
